### ISSUE TITLE
Gravity Forms - Error Saving form 

### ISSUE THREAD

**Issue by mrgrt** [wp-stream/stream#1445]
# Bug Report

## Expected Behavior

Save Gravity form without any errors. 

## Actual Behavior

Save Gravity Form and get an error "There was an error saving your form. To avoid losing your work, click the Save button to save your form and reload the page."

![Screenshot 2023-08-21 at 09 01 30](https://github.com/xwp/stream/assets/1732738/e2b67388-d32f-42f5-a56a-63006c0010d7)

## Steps to Reproduce the Problem

1. Go to Gravity Form 
2. Hit Save to update the form
3. Error shows
4. We have deactivated all other plugins except stream and gravity forms and switched to a default theme. 

## Screenshots/Error logs

![1214385e-3d07-11ee-a417-ae828adb7371](https://github.com/xwp/stream/assets/1732738/b2a8b152-7a90-4947-8e67-024587deb7fd)

## System Information

- Stream plugin version: 3.9.3 
- WordPress version: 6.3
- PHP version: 8.0
- Browser: Chrome 115 
- Computer operating system: macOS (Ventura)

**Comment by kasparsd** [comment]
Thanks for reporting the issue @mrgrt!

The problem appears to be caused by the gravity forms save handler here:

https://github.com/xwp/stream/blob/4fb568dcc82bd8a7102e74c2a60fa5cd9493216c/connectors/class-connector-gravityforms.php#L227-L242

setting some expected placeholder data for the `$message` variable (first argument passed to this method):

https://github.com/xwp/stream/blob/4fb568dcc82bd8a7102e74c2a60fa5cd9493216c/classes/class-connector.php#L170

which is not matching up with the argument list passed to the logger:

https://github.com/xwp/stream/blob/4fb568dcc82bd8a7102e74c2a60fa5cd9493216c/classes/class-log.php#L139

Could it be that your form name or any of the data contains the `%` character? Could you please share the exact form setup to help replicate the issue?
