### ISSUE TITLE
GruntJS workflow

### ISSUE THREAD

**Issue by cfoellmann** [wp-stream/stream#432]
Are you guys interested in setting up GruntJS?
- (re-)generate .pot file
- convert .po to .mo files
- minify css and js files

If you are open for that I would love to send you a PR for that. Just let me know

**Comment by fjarrett** [comment]
Since we are using the [`wp-dev-lib`](https://github.com/xwp/wp-dev-lib) I would rather see these features exist within that project. Some issues have already been presented there.

https://github.com/xwp/wp-dev-lib/issues/46
https://github.com/xwp/wp-dev-lib/issues/32
https://github.com/xwp/wp-dev-lib/issues/47
