### ISSUE TITLE
Is connecting to WordPress.com or with Stream account necessary?

### ISSUE THREAD

**Issue by rnaby** [wp-stream/stream#683]
Is connecting to WordPress.com or with Stream account necessary?
Can't I run this plugin as standalone plugin like others? I don't want to connect to WordPress.com or don't wanna use Stream account. 

Suggestion needed.

**Comment by fjarrett** [comment]
Hi @rnaby,

1. Stream always requires a connection because it's a cloud-based service designed to keep a secure and immutable audit trail of the changes being made to your site. Think [New Relic APM](https://newrelic.com/application-monitoring) for WordPress Admin activity.

2. Using WordPress.com SSO (single sign-on) is a security advantage that prevents Stream from ever needing to store user passwords. This is similar to other 3rd party sign-on methods such as login with Facebook, Twitter or Google.

3. WordPress.com SSO also supports [two-step authentication](http://en.support.wordpress.com/security/two-step-authentication/). This is an important feature for customers who are extra-concerned about the security of their logins, and we wanted Stream to have this capability.

4. The only time the Stream needs to talk to WordPress.com is during sign up, for login credentials. Stream does not "ping" back to the installed plugin (like Jetpack does). This means your site doesn’t have to be publicly accessible for Stream to work and can be run on a local/development environment without any problems or extra steps needed.

Thanks for your question and I hope you find these insights helpful!
